export default {
  products: [
    {
      _id: "1",
      name: "Hiskywin Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "/images/products-1.gif",
      price: 59,
      brand: "Hiskywin",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Shirts",
      image: "https://i.dummyjson.com/data/products/1/1.jpg",
      price: 70,
      brand: "Nike",
      rating: 5,
      numberReviews: 51,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "https://i.dummyjson.com/data/products/1/2.jpg",
      price: 59,
      brand: "Adidas",
      rating: 4,
      numberReviews: 45,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Pants",
      image: "https://i.dummyjson.com/data/products/1/3.jpg",
      price: 90,
      brand: "Under Armour",
      rating: 2.5,
      numberReviews: 198,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Champion Mens Graphic Powerblend Fleece Jogger",
      category: "Pants",
      image: "https://i.dummyjson.com/data/products/1/4.jpg",
      price: 119,
      brand: "Champion",
      rating: 3.5,
      numberReviews: 89,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Aelfric Eden Mens Joggers Pants Long Multi-Pockets",
      category: "Pants",
      image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      price: 85,
      brand: "Aelfric Eden",
      rating: 4.5,
      numberReviews: 45,
      countInStock: 6,
    },
  ],
};
