export default {
  products: [
    {
      _id: "1",
      name: "Ha Noi Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "./images/products-1.gif",
      price: 60,
      brand: "Ha Noi",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Ha Noi Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "./images/products-1.gif",
      price: 60,
      brand: "Ha Noi",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Ha Noi Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "./images/products-1.gif",
      price: 60,
      brand: "Ha Noi",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Ha Noi Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "./images/products-1.gif",
      price: 60,
      brand: "Ha Noi",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Ha Noi Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "./images/products-1.gif",
      price: 60,
      brand: "Ha Noi",
      rating: 4.5,
      numberReviews: 10,
      countInStock: 6,
    },
  ],
};
